### PR TITLE
Add dnf support

### PR DESCRIPTION
**Pull request by mynamewastaken**
Dnf on Fedora 23 wasn't installing the autofs package and was erroring out during a run. I've not done any real testing other than 'it works on my machine'.

### CODE REVIEW

**Comment by mynamewastaken** [comment]
Re: the test failing, it looks like dnf wasn't added until Ansible 1.9, and the test ran with Ansible 1.4.4.

**Comment by cmprescott** [comment]
Try modifying .travis.yml to install newer version of ansible from pip 

Thanks for contributing :+1:

**Comment by mynamewastaken** [comment]
w00t. @cmprescott I can squash when I get home if you like, otherwise feel free. :-)

**Comment by cmprescott** [comment]
PS added tag for 0.2.0 and updated ansible galaxy if you use that to install.

**Comment by mynamewastaken** [comment]
Will do, thanks!

**Pull request merged**
